global using Logis.Models;
global using Logis.Services;
global using Logis.Exceptions;
global using Microsoft.Extensions.AI;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Text.RegularExpressions;
global using System.Security.Cryptography;
global using System.Text;
